linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - exhaustive
    - funlen
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - staticcheck
    - typecheck
    - unused
    - whitespace
  fast: false

linters-settings:
  misspell:
    locale: UK
