builds:
  - main: ./cmd/hansel/
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    hooks:
      post:
        - cmd: "cosign sign-blob --yes --output-certificate dist/{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}-keyless.pem --output-signature dist/{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}-keyless.sig {{ .Path }}"

release:
  extra_files:
    - glob: dist/*.sig
    - glob: dist/*.pem

dockers:
  - &docker
    use: buildx
    dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    image_templates:
      - ghcr.io/shopify/hansel:{{ .Version }}-amd64
    build_flag_templates:
      - --platform=linux/amd64
      - --no-cache
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/Shopify/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/Shopify/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
  - <<: *docker
    goarch: arm64
    image_templates:
      - ghcr.io/shopify/hansel:{{ .Version }}-arm64
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --no-cache
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/Shopify/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/Shopify/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT

docker_manifests:
  - name_template: ghcr.io/shopify/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/shopify/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/shopify/{{ .ProjectName }}:{{ .Version }}-arm64
  - name_template: ghcr.io/shopify/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/shopify/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/shopify/{{ .ProjectName }}:{{ .Version }}-arm64

docker_signs:
  - cmd: cosign
    artifacts: manifests
    output: true
    args:
      - "sign"
      - "${artifact}"
