FROM golang:1.25.5 AS deb
WORKDIR /app
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
ENV HANSEL_TEST_DEBIAN=true
RUN [ "go", "test", "-v", "./internal/cli/...", "-run", "TestGenerate_InstallDebian" ]

# This line also determines the golang version used for GitHub Actions CI
# Use the qualified image name, so Dependabot treats this separate from "golang" above.
FROM docker.io/library/golang:1.25.4-alpine AS apk
ENV CGO_ENABLED=0
WORKDIR /app
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
ENV HANSEL_TEST_ALPINE=true
RUN [ "go", "test", "-v", "./internal/cli/...", "-run", "TestGenerate_InstallAlpine" ]
