FROM golang:1.19rc2 AS deb
WORKDIR /app
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
ENV HANSEL_TEST_DEBIAN=true
RUN [ "go", "test", "-v", "./internal/cli/...", "-run", "TestGenerate_InstallDebian" ]

# This line also determines the golang version used for GitHub Actions CI
FROM golang:1.19rc2 AS apk
ENV CGO_ENABLED=0
WORKDIR /app
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
ENV HANSEL_TEST_ALPINE=true
RUN [ "go", "test", "-v", "./internal/cli/...", "-run", "TestGenerate_InstallAlpine" ]
