#!/bin/bash -e

go run ./cmd/hansel/ \
  --name meow \
  --version 1.0.0 \
  --directory tmp/ \
  --debian \
  --alpine

build() {
    local TARGET="$1"
    docker build --progress plain \
       --target "$TARGET" \
       -t "hansel-$TARGET" .
}

build "alpine"
build "debian"
