name: OpenSSF Scorecard
on:
  branch_protection_rule:
  schedule:
    - cron: '30 1 * * 6'
  push:
    branches: main
  workflow_dispatch:

permissions: {}

jobs:
  analysis:
    permissions:
      contents: read
      id-token: write
    uses: Shopify/github-workflows/.github/workflows/scorecard.yaml@6bad9c35bd35925bc9deea2de30894a057d758dc # v0.1.0
    secrets:
      token: ${{secrets.SCORECARD_TOKEN}}
