name: Scorecard
on:
  branch_protection_rule:
  schedule:
    - cron: '30 1 * * 6'
  push:
    branches: main
  workflow_dispatch:

permissions: {}

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    uses: Shopify/github-workflows/.github/workflows/scorecard.yaml@main # FIXME: pin
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}
